terraform {
  # Remote state in an Azure Storage Account blob container.
  #
  # This is a PARTIAL backend config: the account-specific values live in
  # backend.hcl (generated by ./bootstrap-state.sh, gitignored) and are passed
  # at init time:
  #
  #   ./bootstrap-state.sh           # one-time: creates the state storage
  #   terraform init -backend-config=backend.hcl
  #
  # State is authenticated with your Azure AD identity (no account keys), so the
  # signed-in user needs the "Storage Blob Data Contributor" role on the
  # account (the bootstrap script grants it).
  backend "azurerm" {
    use_azuread_auth = true
  }
}
